"""Initial schema

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create work_items table
    op.create_table('work_items',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('component_id', sa.String(length=100), nullable=False),
        sa.Column('component_type', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=10), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('signal_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create rca_records table
    op.create_table('rca_records',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('work_item_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=False),
        sa.Column('root_cause_category', sa.String(length=50), nullable=False),
        sa.Column('fix_applied', sa.Text(), nullable=False),
        sa.Column('prevention_steps', sa.Text(), nullable=False),
        sa.Column('mttr_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create api_keys table
    op.create_table('api_keys',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('key_hash', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key_hash')
    )
    
    # Create signal_metrics table for TimescaleDB
    op.create_table('signal_metrics',
        sa.Column('time', sa.DateTime(), nullable=False),
        sa.Column('component_id', sa.String(length=100), nullable=True),
        sa.Column('signal_count', sa.Integer(), nullable=False),
        sa.Column('avg_latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.PrimaryKeyConstraint('time')
    )
    
    # Create indexes
    op.create_index('ix_work_items_component_id', 'work_items', ['component_id'])
    op.create_index('ix_work_items_severity_status', 'work_items', ['severity', 'status'])
    op.create_index('ix_work_items_created_at', 'work_items', ['created_at'])
    op.create_index('ix_rca_records_work_item_id', 'rca_records', ['work_item_id'])
    op.create_index('ix_signal_metrics_time', 'signal_metrics', ['time'])
    op.create_index('ix_signal_metrics_component_id', 'signal_metrics', ['component_id'])
    
    # Note: TimescaleDB hypertable creation skipped for Neon compatibility
    # op.execute("SELECT create_hypertable('signal_metrics', 'time');")
    
    # Insert default API key
    import hashlib
    api_key_hash = hashlib.sha256("dev-api-key-12345".encode()).hexdigest()
    op.execute(f"""
        INSERT INTO api_keys (id, key_hash, name, is_active) 
        VALUES (gen_random_uuid(), '{api_key_hash}', 'Development API Key', true);
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_metrics')
    op.drop_table('api_keys')
    op.drop_table('rca_records')
    op.drop_table('work_items')
    # ### end Alembic commands ###
